import Head from 'next/head';
import { ReactNode } from 'react';
import Navbar from './Navbar';
import NextThemeProvider from '../context/NextThemeProvider';

type Props = {
  children?: ReactNode;
  // any props that come into the component
};

function Layout({ children }: Props) {
  return (
    <NextThemeProvider>
      <Head>
        <title>Bloom</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
    </NextThemeProvider>
  );
}

export default Layout;
